### ISSUE TITLE
About installation and implement of vs-net-core-template 

### ISSUE THREAD

**Issue by vgorgen** [ucoruh/vs-net-core-template#1]
In readme file I couldn't understand how I will do and how I will apply. Can you show us how to install and implement the template step by step in the readme file?

**Comment by ucoruh** [comment]
- compare your current repository with current repository you can see changes
- github actions, and batch file and doxygen configurations updated
- README is enough clear to complete this task, when an error occurs then look at logs in github actions you can easily see changes. Your task will be rename and configure some parameters there there is no more operations. But result is better than previous one and you can see doxygen coverage, unit test report and and project website on your local with mkdocs serve
