### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by Aliemree** [ucoruh/vs-net-core-template#2]
![mistake](https://github.com/ucoruh/vs-net-core-template/assets/114071030/cf8fb8c5-f97e-4258-93f6-a21628145db7)
Dear Professor,

Sir we are getting such error. what would you suggest we do?

Ali EMRE
211401026

**Comment by ucoruh** [comment]
Your homework template looks old, you have to update your homework template. Doxygen output is not configured for docs output https://github.com/ucoruh/vs-net-core-template if you didn't synchronize your homework with the latest template we cannot grade your homework with our automation tools. https://github.com/ucoruh/vs-net-core-template/actions/runs/5088996030/jobs/9146139038 Look at the latest builds you can see how it works.  docs/doxygen is the correct folder so we understand that you are not using the new template. 

```
0s
Run tar -czvf doxygen-documents.tar.gz -C docs/doxygen .
  tar -czvf doxygen-documents.tar.gz -C docs/doxygen .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.[1](https://github.com/ucoruh/vs-net-core-template/actions/runs/5088996030/jobs/9146139038#step:36:1)1.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python[2](https://github.com/ucoruh/vs-net-core-template/actions/runs/5088996030/jobs/9146139038#step:36:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/ucoruh/vs-net-core-template/actions/runs/5088996030/jobs/9146139038#step:36:3).11.3/x6[4](https://github.com/ucoruh/vs-net-core-template/actions/runs/5088996030/jobs/9146139038#step:36:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x[6](https://github.com/ucoruh/vs-net-core-template/actions/runs/5088996030/jobs/9146139038#step:36:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib 
```
